JAPI-512 Github action based HPCC/Spark evn for junit tests
hpcc-systems/Spark-HPCC pull request #127
Opened 2023-06-30 14:20 UTC by jpmcmu

- Modified Github actions to test against a K8s HPCC cluster
- Modified Spark JUnits to use mvn integration tests
- Modified Spark integration tests to use Datasource API
- Removed outdated tests
- Modified POM file to fix dependency conflicts

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

2023-06-30 14:20 UTC, jpmcmu commented
@rpastrana please review

2023-06-30 15:10 UTC, rpastrana requested changes
@jpmcmu looks good, left a few comments

2023-07-17 14:32 UTC, rpastrana reviewed
@jpmcmu looks good, had a couple of questions.

2023-07-17 14:32 UTC, rpastrana commented on .github/workflows/spark-hpcc-remote-test.yml
> +            spark-url: https://archive.apache.org/dist/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz
are these pulled every time?

2023-07-17 14:32 UTC, rpastrana commented on .github/workflows/sparkconnectorbuildonmerge.yml
> -name: HPCC Spark connector build on merge
It seems fine to remove this action, but we do need to ensure the build doesn't break upon a merge onto candidate-* and or master. Any reason not to trigger spark-hpcc-remote-test.yml on push?

2023-07-17 15:13 UTC, jpmcmu commented on .github/workflows/spark-hpcc-remote-test.yml
> +            spark-url: https://archive.apache.org/dist/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2.tgz
Good question, I have a change in the version that includes the changes from HPCCJ-523 that will won't require a redownload. Will push that up after HPCC4J-523 is merged.

2023-07-18 15:26 UTC, merged