HPCC4J-613 Spark-hpcc connector trace context propagation
hpcc-systems/Spark-HPCC pull request #144
Opened 2024-08-12 16:16 UTC by jpmcmu

- Added opentelemetry support
- Added example usage and documentation information

Signed-off-by: James McMullan James.McMullan@lexisnexis.com

2024-08-12 16:16 UTC, jpmcmu commented
@rpastrana please review

2024-08-12 16:39 UTC, jpmcmu commented
Example Tracing output:
![Screenshot 2024-08-12 at 12 07 53 PM](https://github.com/user-attachments/assets/15d9eba2-63ea-4cdb-aa61-025039dd1910)

2024-08-12 17:36 UTC, rpastrana reviewed
@jpmcmu a few comments

2024-08-12 17:36 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
> +        Utils.getOpenTelemetry();
can this be done earlier in the process?

2024-08-12 17:36 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
> +        Span createFileSpan = Utils.createChildSpan(traceID, spanID, "HpccFileWriter.Write/CreateFile_" + fileName);
are we expected to have a parent span representing the hpccfilewriter.write activity at this point? If so, this child span name could be reduced to just CreateFile_+filename

2024-08-12 17:36 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
> +        Span repartSpan = Utils.createChildSpan(traceID, spanID, "HpccFileWriter.Write/Repartition_" + fileName);
similar comment regarding the span name

2024-08-12 17:36 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
> +
very minor extra new lines.

2024-08-12 17:36 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
> +            filePartWriteSpan.setStatus(StatusCode.OK);
If this works as expected, we should set the status to ok earlier and move L:407 up.
Also, now we can add the filePartWriteSpan.end(); calls in a finally block

2024-08-12 17:36 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
> +        issueWriteSpan.setStatus(StatusCode.OK);
set this status earlier as was done in other similar block

2024-08-12 17:36 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
> +        publishFileSpan.setStatus(StatusCode.OK);
move setstatus up, add end call to finally

2024-08-12 17:36 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/Utils.java
> +    static {
minor, move curly to new line

2024-08-12 17:36 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/Utils.java
> +        System.setProperty("otel.service.name", "org.hpccsystems.spark");
I'm not sure if we're doing this in other hpcc4j components, we should if not.

2024-08-12 17:36 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/Utils.java
> +            if (Boolean.getBoolean("otel.java.global-autoconfigure.enabled"))
does the java-agent zerocode instrumentation expect to be autoconfigured? if so I thought the AutoConfiguredOpenTelemetrySdk.initialize().getOpenTelemetrySdk() caused a warning.

2024-08-12 17:46 UTC, rpastrana commented
@jpmcmu reviewed. Also, Examples/PySparkExample.ipynb has a conflict.

2024-08-12 17:54 UTC, rpastrana commented
> Example Tracing output: ![Screenshot 2024-08-12 at 12 07 53 PM](https://private-user-images.githubusercontent.com/7181610/357130165-15d9eba2-63ea-4cdb-aa61-025039dd1910.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0ODQ0ODksIm5iZiI6MTcyMzQ4NDE4OSwicGF0aCI6Ii83MTgxNjEwLzM1NzEzMDE2NS0xNWQ5ZWJhMi02M2VhLTRjZGItYWE2MS0wMjUwMzlkZDE5MTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMTczNjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjAzMzU2N2I2ZTFjMGVlZTQ4MDg2NTkzN2QzMmYxNTY2MWI0YzlhYWZmNjI2YzUyYTlkMGQwNmY4Njc1Y2IzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GYMzF35LAIqF3qkWm-oQmwWw_OvOIPIYKIMj6Hmwdjk)

Looking over the screenshot answers some of my review questions.
The SparkWriteSpan children names are fine, but perhaps a bit overly verbose. Also do we think the gap is due to missing dafilserv span? Can we also configure the HPCC to report its traces?

2024-08-13 13:27 UTC, jpmcmu commented
@rpastrana pushed up code review changes. The gaps appear to be from work Spark is doing, I believe it is the time it takes for the Spark scheduler to issue the write tasks to the Spark cluster and for them to picked up / executed.

2024-08-13 17:03 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java
> +  private String traceID = "";
did we decide to track trace/span ids as strings instead of an otel span for serialization purposes?

2024-08-13 17:05 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java
> +    this.traceID = span.getSpanContext().getTraceId();
it might be necessary to ensure the span is valid, otherwise we might try to assign internal spans as children of an invalid span

2024-08-13 17:20 UTC, rpastrana requested changes
@jpmcmu

2024-08-13 17:20 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java
> +  private String spanID = "";
also, is this trace and span ID the parentTrace/parentSpan ID ? if so, let's label it as such.

2024-08-13 17:20 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFile.java
> +	  HpccRDD rdd = new HpccRDD(sc, getFileParts(), this.getRecordDefinition(), this.getProjectedRecordDefinition(), this.getFileAccessExpirySecs(), this.recordLimit);
minor format issue, curly in new line.

2024-08-13 17:20 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
> +    private String                    traceID               = "";
parent trace?

2024-08-13 17:20 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
> +        this.traceID = traceID;
does it make sense to track if trace/span are invalid?

2024-08-13 17:20 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
> +        createFileSpan.setStatus(StatusCode.OK);
I thought this line was moving up and overwritten in the catch block, and the span.end in a finally clause

2024-08-13 17:20 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
> +            filePartWriteSpan.setStatus(StatusCode.OK);
Does the setStatus call work as you expect it to work here? if so we should be consistent, other spans seem to set status to ok at the end.

2024-08-13 17:20 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
>              }
any reason not to end the span in a finally clause?

2024-08-13 17:20 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccFileWriter.java
> +        issueWriteSpan.setStatus(StatusCode.OK);
above comment still applies

2024-08-13 17:20 UTC, rpastrana commented on DataAccess/src/main/java/org/hpccsystems/spark/HpccRDD.java
> +    private String                     traceID = "";
parent Trace/Span ID?

2024-08-14 14:46 UTC, jpmcmu commented
@rpastrana Pushed up code review changes, if it looks good will squash

2024-08-15 14:57 UTC, rpastrana approved these changes

2024-08-15 14:57 UTC, merged